project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Guide d'installation des LLM"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: I-Accompagnement/1_Besoins.qmd
        text: "Accompagnement"
      - href: II-Developpements/1_Revue_Technique_LLM.qmd
        text: "Developpements"
      - href: III-Deploiements/1_Socle_minimal.qmd
        text: "Deploiements"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true